version: '3'

services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - '6543:8080'
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock:/home/wiremock